### ISSUE TITLE
Using with other protocols

### ISSUE THREAD

**Issue by HosseyNJF** [mtigas/iObfs#6]
Hi. Can this library be used in other protocols, such as OpenVPN in iOS?

Also, looks like this project isn't being updated. Is it still safe to use, or is deprecated؟

**Comment by tladesignz** [comment]
It should be safe to use but I suggest to use this here now: http://github.com/tladesignz/IPtProxy

**Comment by mtigas** [comment]
Yep. Gonna start pointing to https://github.com/tladesignz/IPtProxy now.
