### ISSUE TITLE
Mark deprecated and advertise IPtProxy as an alternative

### ISSUE THREAD

**Issue by tladesignz** [mtigas/iObfs#7]
Mike, I was tasked to add Snowflake to Onion Browser.

This is the result:
http://github.com/tladesignz/IPtProxy

It also uses the latest Obfsproxy.

So that makes this lib outdated. Maybe you want to mark this deprecated and advertise IPtProxy instead?

Thank you!

**Comment by mtigas** [comment]
Excellent. Will do, and will mark this repo as "archived" after I add some notes / links to the new lib.
